### ISSUE TITLE
Button See more dont work

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#21]
The linkable area of ​​the button is not right.

https://user-images.githubusercontent.com/1231955/228748153-1b22908f-fc25-40c3-9bbc-bbcb069f4dff.mov

**Comment by pyotrsky** [comment]
This is under the trending section in home page, right? @ladopixel

**Comment by ladopixel** [comment]
@pyotrsky yes

**Comment by imght** [comment]
Hello, the mentioned problem was investigated, but since this problem did not happen to us, we could not find the source and solve it. We would be grateful if you could
1. check this problem with your browser or other devices and see if the problem exists for other platforms as well. If the problem is solved with these changes, please mention the browser and operating system that this problem happened to you while using it.
2. Also, if this happened to you in a particular situation, describe that situation (anything , such as page length or width, ...).

thanks.

**Comment by ladopixel** [comment]
I just did the test from another browser and the same thing happens, when I inspect the element I see that there is an image that has a gradient and occupies half the screen. I guess you will have to send that image with z-index behind the button.

With Chrome and Brave.

![Captura de Pantalla 2023-04-02 a las 21 07 14](https://user-images.githubusercontent.com/1231955/229373841-34353a7b-68c0-4f77-a418-55b097d9c35c.png)

**Comment by ladopixel** [comment]
Adding z-index: 2 to the button solves the problem. 
Obviously adding the style directly to the html as I did is not the best way...

![Captura de Pantalla 2023-04-02 a las 21 18 48](https://user-images.githubusercontent.com/1231955/229374273-d9148d0f-3df0-4688-bbad-a243b05086ac.png)

**Comment by imght** [comment]
Thank you for your help and guidance. With your assistance, I believe I have successfully resolved the issue. Could you please test it again and let us know if the problem persists?

**Comment by anon-real** [comment]
This has been resolved. @ladopixel please report if this happens again.
